apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: student-absence-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: hiba7830/student-absence-app-backend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: student-absence-dev
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
