apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: student-absence-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hiba7830/student-absence-app-frontend:latest
          ports:
            - containerPort: 19000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: student-absence-dev
spec:
  selector:
    app: frontend
  ports:
    - port: 19000
      targetPort: 19000
