- name: Deploy to Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Apply Kubernetes configs
      shell: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
